version: '2'

services:
  bot:
    build: .
    ports:
      - "5555:5555"
    container_name: food-adviser-bot
    volumes:
      - ./data/:/root/db/
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    container_name: food-adviser-bot-db
    stdin_open: true
    tty: true
    volumes:
      - ./data/:/root/db/


